# source file list - not including test benches
# for use by efinity
core/hdl/UlpiFSLSEmul.vhd
core/hdl/UlpiIOBuf.vhd
core/hdl/UlpiIO.vhd
core/hdl/UlpiLineState.vhd
core/hdl/UlpiLogger.vhd
core/hdl/UlpiPkg.vhd
core/hdl/Usb2AppCfgPkg.vhd
core/hdl/Usb2Bram.vhd
core/hdl/Usb2CCSync.vhd
core/hdl/Usb2Core.vhd
core/hdl/Usb2DescPkg.vhd
core/hdl/Usb2FSLSRxBitShift.vhd
core/hdl/Usb2FSLSRx.vhd
core/hdl/Usb2FSLSTx.vhd
core/hdl/Usb2MboxSync.vhd
core/hdl/Usb2Pkg.vhd
core/hdl/Usb2PktProc.vhd
core/hdl/Usb2PktRx.vhd
core/hdl/Usb2PktTx.vhd
core/hdl/Usb2PrivPkg.vhd
core/hdl/Usb2StdCtlEp.vhd
core/hdl/Usb2StrmBuf.vhd
core/hdl/Usb2UtilPkg.vhd
core/hdl/UsbCrcTbl.vhd
endpoints/AUDIO/hdl/Usb2EpAudioCtl.vhd
endpoints/AUDIO/hdl/Usb2EpAudioInpStrm.vhd
endpoints/AUDIO/hdl/Usb2EpBADDSpkr.vhd
endpoints/AUDIO/hdl/Usb2EpI2SPlayback.vhd
endpoints/CDCACM/hdl/Usb2EpCDCACMCtl.vhd
endpoints/CDCACM/hdl/Usb2EpCDCACMNotify.vhd
endpoints/CDCACM/hdl/Usb2EpCDCACM.vhd
endpoints/CDCECM/hdl/Usb2EpCDCECM.vhd
endpoints/CDCNCM/hdl/Usb2EpCDCNCMCtl.vhd
endpoints/CDCNCM/hdl/Usb2EpCDCNCMInp.vhd
endpoints/CDCNCM/hdl/Usb2EpCDCNCMOut.vhd
endpoints/CDCNCM/hdl/Usb2EpCDCNCM.vhd
endpoints/common/hdl/Usb2EpCDCEtherNotify.vhd
endpoints/common/hdl/Usb2EpGenericCtlPkg.vhd
endpoints/common/hdl/Usb2EpGenericCtl.vhd
endpoints/common/hdl/Usb2FifoEp.vhd
endpoints/common/hdl/Usb2Fifo.vhd
endpoints/common/hdl/Usb2MuxEpCtlPkg.vhd
endpoints/common/hdl/Usb2MuxEpCtl.vhd
example/hdl/StdLogPkg.vhd
example/hdl/Usb2ExampleDev.vhd
