set_property PACKAGE_PIN T20 [get_ports {JB1_P}]
set_property PACKAGE_PIN U20 [get_ports {JB1_N}]
set_property PACKAGE_PIN V20 [get_ports {JB2_P}]
#set_property PACKAGE_PIN W20 [get_ports {JB2_N}]
set_property PACKAGE_PIN Y18 [get_ports {JB3_P}]
#set_property PACKAGE_PIN Y19 [get_ports {JB3_N}]
set_property PACKAGE_PIN W18 [get_ports {JB4_P}]
#set_property PACKAGE_PIN W19 [get_ports {JB4_N}]

set_property PACKAGE_PIN V15 [get_ports {JC1_P}]
#set_property PACKAGE_PIN W15 [get_ports {JC1_N}]
set_property PACKAGE_PIN T11 [get_ports {JC2_P}]
#set_property PACKAGE_PIN T10 [get_ports {JC2_N}]
set_property PACKAGE_PIN W14 [get_ports {JC3_P}]
#set_property PACKAGE_PIN Y14 [get_ports {JC3_N}]
set_property PACKAGE_PIN T12 [get_ports {JC4_P}]
#set_property PACKAGE_PIN U12 [get_ports {JC4_N}]

set_property PACKAGE_PIN T14 [get_ports {JD1_P}]
#set_property PACKAGE_PIN T15 [get_ports {JD1_N}]
set_property PACKAGE_PIN P14 [get_ports {JD2_P}]
#set_property PACKAGE_PIN R14 [get_ports {JD2_N}]
set_property PACKAGE_PIN U14 [get_ports {JD3_P}]
#set_property PACKAGE_PIN U15 [get_ports {JD3_N}]
set_property PACKAGE_PIN V17 [get_ports {JD4_P}]
#set_property PACKAGE_PIN V18 [get_ports {JD4_N}]

set_property PACKAGE_PIN H16 [get_ports {HDMI_CLK_P}]

set_property IOSTANDARD LVCMOS33 [get_ports -regex {J[BCD][1-4]_[PN]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_CLK_P}]
